### ISSUE TITLE
problem-installing difmap

### ISSUE THREAD

**Issue by emadika** [kazuakiyama/homebrew-difmap#2]
Hi!

I am new to installing difmap and came across the error below after the: brew install difmap command. I am having Ventura 13.6.3. 
Do you know how I can proceed? 

Thank you very much!
Eftychia M. 

==> ./makeall
Last 15 lines from /Users/emadika/Library/Logs/Homebrew/difmap/03.makeall:
gcc -c -O -Dintel_osx -I/private/tmp/difmap-20240103-19064-qhjji5/uvf_difmap_2.5p/include lmfit.c
gcc -c -O -Dintel_osx -I/private/tmp/difmap-20240103-19064-qhjji5/uvf_difmap_2.5p/include matinv.c
gcc -c -O -Dintel_osx -I/private/tmp/difmap-20240103-19064-qhjji5/uvf_difmap_2.5p/include newfft.c
gcc -c -O -Dintel_osx -I/private/tmp/difmap-20240103-19064-qhjji5/uvf_difmap_2.5p/include model.c
touch modvis.h
gcc -c -O -Dintel_osx -I/private/tmp/difmap-20240103-19064-qhjji5/uvf_difmap_2.5p/include modvis.c
gcc -c -O -Dintel_osx -I/private/tmp/difmap-20240103-19064-qhjji5/uvf_difmap_2.5p/include besj.c
gcc -c -O -Dintel_osx -I/private/tmp/difmap-20240103-19064-qhjji5/uvf_difmap_2.5p/include addmod.c
gcc -c -O -Dintel_osx -I/private/tmp/difmap-20240103-19064-qhjji5/uvf_difmap_2.5p/include modfit.c
gcc -c -O -Dintel_osx -I/private/tmp/difmap-20240103-19064-qhjji5/uvf_difmap_2.5p/include modeltab.c
gfortran -o difmap  startup.o f77main.o difmap.o slfcal.o wmapbeam.o maplot.o moddif.o vlbhead.o uvaver.o mapmem.o mapclean.o mapres.o costran.o uvinvert.o clphs.o clplot.o vlbhist.o enumpar.o symtab.o plbeam.o uvrotate.o stnstr.o uvtrans.o corplt.o modplot.o uvradplt.o vedit.o vplot.o color.o uvplot.o timplt.o specplot.o markerlist.o uvf_read.o uvf_write.o obs.o subarray.o obutil.o binan.o dpage.o if.o ifpage.o intrec.o obedit.o obhead.o uvpage.o chlist.o obpol.o telcor.o visaver.o utbin.o intlist.o obshift.o resoff.o winmod.o subamphs.o addamphs.o nextif.o wtscal.o units.o scans.o mapwin.o stokes.o visstat.o pb.o mapcor.o hms.o termstr.o visflags.o telspec.o ellips.o uvrange.o baselist.o spectra.o pollist.o freelist.o planet.o cksum.o fnint.o dnint.o frange.o imran.o minmax.o lmfit.o matinv.o newfft.o  model.o modvis.o besj.o addmod.o modfit.o modeltab.o -L/private/tmp/difmap-20240103-19064-qhjji5/uvf_difmap_2.5p/lib -lsphere -L/private/tmp/difmap-20240103-19064-qhjji5/uvf_difmap_2.5p/lib -llogio -L/private/tmp/difmap-20240103-19064-qhjji5/uvf_difmap_2.5p/lib -lpager -L/private/tmp/difmap-20240103-19064-qhjji5/uvf_difmap_2.5p/lib -lcpgplot -L/usr/local/lib -lpgplot -lX11 -lpng -L/private/tmp/difmap-20240103-19064-qhjji5/uvf_difmap_2.5p/lib -lfits -L/private/tmp/difmap-20240103-19064-qhjji5/uvf_difmap_2.5p/lib -lrecio -L/private/tmp/difmap-20240103-19064-qhjji5/uvf_difmap_2.5p/lib -lscrfil -L/private/tmp/difmap-20240103-19064-qhjji5/uvf_difmap_2.5p/lib -lslalib -ltecla -lcurses /usr/local/Cellar/gcc/13.2.0/bin/../lib/gcc/current/gcc/x86_64-apple-darwin20/13/libgcc.a      /System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation      /System/Library/Frameworks/AppKit.framework/Versions/Current/AppKit -lm
ld: warning: ignoring duplicate libraries: '-lgcc', '-lgcc_s.1.1'
ld: multiple errors: file cannot be open()ed, errno=2 path=/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation in '/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation'; file cannot be open()ed, errno=2 path=/System/Library/Frameworks/AppKit.framework/Versions/Current/AppKit in '/System/Library/Frameworks/AppKit.framework/Versions/Current/AppKit'
collect2: error: ld returned 1 exit status
make: *** [/private/tmp/difmap-20240103-19064-qhjji5/uvf_difmap_2.5p/difmap] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/kazuakiyama/homebrew-difmap/issues

**Comment by kazuakiyama** [comment]
Hello, sorry that I wasn't able to respond earlier. I took a look at source code and identified what are the likely issues. Recent macOS doesn't have the following two directories specified in the original configure file for $CCLIB. - /System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation
- /System/Library/Frameworks/AppKit.framework/Versions/Current/AppKit
As I don't understand what these directories are supposed to have, I will contact the DIFMAP developers for suggestions. Ultimately this should be an issue of DIFMAP configuration file rather than this formula, so I will see if this can be fixed on their side or simply I should provide an ad-hoc fix for this particular formula.

**Comment by kazuakiyama** [comment]
Hi, so now, I modified to fix it in an ad-hoc way. Please try
```
brew untap kazuakiyama/difmap
brew tap kazuakiyama/difmap
brew install difmap
```
OR
```
brew update
brew install difmap 
```

I compiled it in both intel and M1 mac, and it looks working ok.

**Comment by kazuakiyama** [comment]
@emadika Now I have released a new formula for the lastest difmap version 2.5q. Please try one more time. You can do by either of the sets of commands I wrote earlier.
